name: Auto commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=$(date '+%Y-%m-%dT%H:%M:%SZ')
          echo "Last update on $d" > LAST_UPDATED.tsx

      - name: Commit changes
        run: |
          git config --local user.email "rxmxdhxni@gmail.com"
          git config --local user.name "dante4rt"
          git add -A
          
          arr=("chore(bot): 💀" "chore(bot): 🎹" "chore(bot): 🎼" "chore(bot): ⚙️" "chore(bot): ⚔️" "chore(bot): 💜" "chore(bot): 🌸" "chore(bot): 💍" "chore(bot): ❄️" "chore(bot): 🫧")
          rand=$RANDOM % ${#arr[@]}
          
          git commit -m "${arr[rand]}"

      - name: Push Changes
        run: git push origin main